FROM  oven/bun:1

WORKDIR /usr/src/app
ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 8080

CMD [ "bun" ,"run", "start:backend" ]
