FROM  oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/web ./apps/web

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN bun install
RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD [ "bun" ,"run", "start:web" ]
